### ISSUE TITLE
Make crit commands skip the user's own submissions

### ISSUE THREAD

**Issue by marekceglowski** [marekceglowski/DiscordGroupCritter#13]
Right now the crit command can return any submission. Before returning it we should check if it belongs to the user that ran the command, and if so, return the next (or another random) one. Loop it so it keeps checking until a submission is not from the same user anymore.

**Comment by will-jj** [comment]
could this be done with something like the following? (not tested yet, syntax might be a bit wonky)

```python 
def get_ordered_queue_submissions(user_id=None):
    submissions = db.submissions.find( {{'status':'pending'},{ 'user_id': { $ne: user_id} }} )

   ```
